### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by nimtaraMunasinghe** [nimtaraMunasinghe/hotel-reservation-system#1]
I will design the footer

**Comment by nimtaraMunasinghe** [comment]
In footer hr, there is a small arrow in the beginning.  I have no idea why.
` <div class="footer-hr">
           <hr>
       </div>`

`.footer-hr hr{
    width: 85%;
    border-width: 2px;
    margin: auto;
}`

**Comment by christancf** [comment]
Issue solved
